site_name: dayer.local

nav:
  - Home: index.md
  - Blog:
      - blog/index.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand

plugins:
  - search
  - blog:
      blog_dir: blog
      authors_file: blog/.authors.yml
      blog_toc: true

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css